repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: sort-simple-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml

  - repo: local
    hooks:
      - id: isort
        name: isort
        pass_filenames: false
        entry: poetry run isort .
        language: python

      - id: black
        name: black
        pass_filenames: false
        entry: poetry run black .
        language: python

      - id: ruff
        name: ruff
        pass_filenames: false
        entry: poetry run ruff --fix .
        language: python

      - id: pytest
        name: tests
        pass_filenames: false
        entry: poetry run pytest tests/ -q
        language: python
