on:
  pull_request:
    branches:
      - master
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install --only dev,tests

      - name: Format
        run: |
          poetry run isort --check-only --diff ./
          poetry run black --check --diff ./

      - name: Lint
        run: poetry run ruff ./

      - name: Run Tests
        run: poetry run pytest tests/
